# Generated by Django 5.0.1 on 2024-01-16 01:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0007_pet_pid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cart',
            new_name='petcart',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pid',
        ),
    ]
