# Generated by Django 5.0.1 on 2024-01-23 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0010_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.IntegerField(),
        ),
    ]
